name: ekikrit
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  get_storage: ^2.0.3
  google_fonts: ^4.0.0
  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.0
  carousel_slider: ^4.1.1
  persistent_bottom_nav_bar: ^5.0.2
  dio: ^4.0.6
  dio_smart_retry: ^1.0.0
  email_validator: ^2.1.17
  flutter_inappwebview: ^5.7.2+3
  #  flutter_inappwebview: ^6.0.0-beta.24+1
  webview_flutter: ^4.2.2
  url_launcher: ^6.1.7
  permission_handler: ^10.2.0
  flutter_otp_text_field: ^1.1.1
  lottie: ^2.3.0
  image_picker: ^0.8.7+1
  url_strategy: ^0.2.0
  flutter_stripe: ^9.0.0+1
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^15.1.0+1
  firebase_core: ^2.13.0
  firebase_messaging: ^14.6.1
  uuid: ^3.0.7
  google_fonts: ^4.0.3
  font_awesome_flutter: ^10.4.0
  device_info_plus: ^8.2.0
  cached_network_image: ^3.2.0
  get: ^4.6.5
  get_storage: ^2.0.3
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.8.2
  path_provider: ^2.0.15
  dio: ^4.0.6
  dio_smart_retry: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/drawer-consumer/
    - assets/your-account/
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/onboarding/
    - assets/i18n/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
